Repository Swat-FastOrder/Backend, pull requests merged in 2020-12, with the labels that each got.

#57 bugfix(update_user_migration): remove duplicated is_availale field
  src/modules/database/migrations/1606847894690-update_user_table.ts
Labels: backend, bug

#56 feat(roles): get all roles
  src/app.module.ts
  src/modules/role/dto/role-response.dto.ts
  src/modules/role/role.controller.ts
  src/modules/role/role.entity.ts
  src/modules/role/role.module.ts
  src/modules/role/role.repository.ts
  src/modules/role/role.service.ts
Labels: backend, enhancement

#62 Feature/email module
  .env.sample
  .gitignore
  package.json
  src/app.module.ts
  src/modules/config/config.enum.ts
  src/modules/config/config.service.ts
  src/modules/user/user.service.ts
  src/modules/utils/email-welcome-template.ts
Labels: backend, enhancement

#64 Fix/dish creation
  src/modules/menu-dishes/menu-dishes.module.ts
  src/modules/menu-dishes/menu-dishes.service.ts
Labels: backend, enhancement

#72 feat(order-details): Create correct relations between order_details
  src/modules/menu-dishes/dtos/menu-dishes-response.dto.ts
  src/modules/order-detail/dto/order-detail-response.dto.ts
  src/modules/order-detail/order-detail.entity.ts
  src/modules/order-detail/order-detail.service.ts
Labels: refactor

#77 :sparkles: feature(mail)Add login url variable and add in template
  .env.sample
  src/modules/config/config.enum.ts
  src/modules/user/user.module.ts
  src/modules/user/user.service.ts
  src/modules/utils/email-welcome-template.ts
Labels: backend, enhancement
